### ISSUE TITLE
Theme template for displaying information about Journal papers

### ISSUE THREAD

**Issue by philbarker** [philbarker/pubwp#14]
Tracking bug for work on sharing and learning theme
- [x] Create empty template
- [x] Display title
- [x] Display common properties
- [x] Display author info
- [x] Display journal details
- [x] Display pagination

**Depends on solving** 
- [x] #16 functions for Person info
- [x] #15 functions for Common info 
- [x] #18 functions for Journal info 

- Should include any schema.org markup that is not in functions (e.g. wrap whole description in schema.org:Article )

**Comment by philbarker** [comment]
Closed by https://github.com/philbarker/sharinglearning_theme/commit/7fbd5f646f58c5836b63a559c6c4548121cb662a
